version: '3'

dotenv: ['.env']

env:
  GOWORK: off

vars:
  WISE_PORT: '{{.WISE_PORT | default "8080"}}'

tasks:
  default:
    desc: Show available tasks
    cmds:
      - xplat task --list

  debug:
    desc: Print environment variables
    cmds:
      - echo "WISE_API_TOKEN=$WISE_API_TOKEN"
      - echo "PLAT_BIN=$PLAT_BIN"

  rates:
    desc: Get exchange rates from Wise API
    cmds:
      - go run ./cmd/wise-cli -cmd rates

  profiles:
    desc: List Wise profiles
    cmds:
      - go run ./cmd/wise-cli -cmd profiles

  balances:
    desc: Show account balances
    cmds:
      - go run ./cmd/wise-cli -cmd balances

  statements:
    desc: Show transaction history (last 30 days)
    cmds:
      - go run ./cmd/wise-cli -cmd statements

  quote:
    desc: Get a quote (use -- -from USD -to EUR -amount 100)
    cmds:
      - go run ./cmd/wise-cli -cmd quote {{.CLI_ARGS}}

  rate-history:
    desc: Get rate history (use -- -from EUR -to USD -days 7)
    cmds:
      - go run ./cmd/wise-cli -cmd rate-history {{.CLI_ARGS}}

  mcp:
    desc: Run the MCP server for Claude integration
    cmds:
      - go run ./cmd/wise-mcp

  mcp-build:
    desc: Build the MCP server binary
    cmds:
      - go build -o $PLAT_BIN/wise-mcp ./cmd/wise-mcp

  mcp-config:
    desc: Print Claude Desktop MCP config snippet
    cmds:
      - |
        echo 'Add to ~/Library/Application Support/Claude/claude_desktop_config.json:'
        echo ''
        cat <<EOF
        {
          "mcpServers": {
            "wise": {
              "command": "$(pwd)/$PLAT_BIN/wise-mcp",
              "env": {
                "WISE_API_TOKEN": "YOUR_TOKEN_HERE"
              }
            }
          }
        }
        EOF

  serve:
    desc: Start web GUI dashboard
    cmds:
      - go run ./cmd/wise-server -port {{.WISE_PORT}}

  serve-build:
    desc: Build web server binary
    cmds:
      - go build -o $PLAT_BIN/wise-server ./cmd/wise-server

  build:
    desc: Build all binaries
    deps: [build-dir]
    cmds:
      - go build -o $PLAT_BIN/wise-cli ./cmd/wise-cli
      - go build -o $PLAT_BIN/wise-mcp ./cmd/wise-mcp
      - go build -o $PLAT_BIN/wise-server ./cmd/wise-server

  build-dir:
    desc: Create build directory
    cmds:
      - xplat os mkdir $PLAT_BIN
    status:
      - test -d $PLAT_BIN

  test:
    desc: Run tests
    cmds:
      - go test ./...

  clean:
    desc: Remove built binaries
    cmds:
      - xplat os rm -rf $PLAT_BIN

  up:
    desc: Start all services with process-compose
    cmds:
      - xplat process up

  down:
    desc: Stop all services
    cmds:
      - xplat process down
